// Delphi 3 *************************************
{$IFDEF VER100}

{$ENDIF}

// Delphi 4 *************************************
{$IFDEF VER120}

{$ENDIF}

// Delphi 5 *************************************
{$IFDEF VER130}

{$ENDIF}

// Delphi 6 *************************************
{$IFDEF VER140}
  {$DEFINE VARIANTS}
{$ENDIF}

// Delphi 7 *************************************
{$IFDEF VER150}
  {$DEFINE VARIANTS}
  {$DEFINE XPSTYLE}
{$ENDIF}

